var helperBarcode = require('./barcode');
var helperClass = require('./class');
var helperColumn = require('./column');
var helperColumns = require('./columns');
var helperEach = require('./each');
var helperFont = require('./font');
var helperHeader = require('./header');
var helperIf = require('./if');
var helperImage = require('./image');
var helperList = require('./list');
var helperPageBreak = require('./pageBreak');
var helperPageFooter = require('./pageFooter');
var helperPageHeader = require('./pageHeader');
var helperQr = require('./qr');
var helperResetPageCount = require('./resetPageCount');
var helperRow = require('./row');
var helperSpacer = require('./spacer');
var helperStack = require('./stack');
var helperSvg = require('./svg');
var helperTable = require('./table');
var helperText = require('./text');

module.exports = function(compiler) {
  helperBarcode(compiler);
  helperClass(compiler);
  helperColumn(compiler);
  helperColumns(compiler);
  helperEach(compiler);
  helperFont(compiler);
  helperHeader(compiler);
  helperIf(compiler);
  helperImage(compiler);
  helperList(compiler);
  helperPageBreak(compiler);
  helperPageFooter(compiler);
  helperPageHeader(compiler);
  helperQr(compiler);
  helperResetPageCount(compiler);
  helperRow(compiler);
  helperSpacer(compiler);
  helperStack(compiler);
  helperSvg(compiler);
  helperTable(compiler);
  helperText(compiler);
};
