var helperColumn = require('./column');
var helperColumns = require('./columns');
var helperEach = require('./each');
var helperHeader = require('./header');
var helperIf = require('./if');
var helperImage = require('./image');
var helperList = require('./list');
var helperPageFooter = require('./pageFooter');
var helperPageHeader = require('./pageHeader');
var helperQr = require('./qr');
var helperResetPageCount = require('./resetPageCount');
var helperRow = require('./row');
var helperSvg = require('./svg');
var helperTable = require('./table');
var helperText = require('./text');

module.exports = function(compiler) {
  helperColumn(compiler);
  helperColumns(compiler);
  helperEach(compiler);
  helperHeader(compiler);
  helperIf(compiler);
  helperImage(compiler);
  helperList(compiler);
  helperPageFooter(compiler);
  helperPageHeader(compiler);
  helperQr(compiler);
  helperResetPageCount(compiler);
  helperRow(compiler);
  helperSvg(compiler);
  helperTable(compiler);
  helperText(compiler);
};
